services:
  postgres:
    image: postgres:16
    container_name: reddit_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  kafka:
    image: apache/kafka:4.3.1
    container_name: reddit_kafka
    ports:
      - "9092:9092"